server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 175.24.174.14:8848 # nacos服务地址
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyId: LTAI5tLXyPneD2fwy7eZ19N7
    keySecret: 20sr3wAUSzJCHjL76uJc4CmZM4T8pk
    bucketName: wanfeng-oss